version: '3'

networks:
 longbow:
    driver: bridge

services:
  neo4j:
    image: neo4j:3.4
    hostname: neo4j
    container_name: neo4j
    ports:
    - "7474:7474"
    - "7687:7687"
    depends_on:
    - kafka
    volumes:
    - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/neo
      NEO4J_dbms_logs_debug_level: DEBUG
      # KAFKA related configuration
      NEO4J_kafka_zookeeper_connect: zookeeper:12181
      NEO4J_kafka_bootstrap_servers: kafka:19092
      NEO4J_streams_source_enabled: "true"
      NEO4J_streams_source_schema_polling_interval: 10000
    networks:
    - longbow

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
    - "12181:12181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 12181
    networks:
      - longbow

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
    - "19092:19092"
    depends_on:
    - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "nodes:1:3"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092
      KAFKA_ADVERTISED_HOST_NAME: 'kafka'
    networks:
      - longbow